# Generated by Django 3.0.1 on 2020-10-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200902_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='puples',
            name='education_level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень в системе решения задач'),
        ),
    ]
