# Generated by Django 3.0.1 on 2020-10-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_puples_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='puples',
            name='language_stack',
            field=models.CharField(blank=True, max_length=200, verbose_name='Список языков программирования, которыми владеет(через запятую)'),
        ),
    ]
