# Generated by Django 3.0.1 on 2020-11-01 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_puples_language_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puples',
            name='education_level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Уровень в системе решения задач'),
        ),
    ]
