# Generated by Django 3.0.1 on 2020-12-09 13:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20201101_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puples',
            name='language_stack',
        ),
        migrations.AddField(
            model_name='puples',
            name='task_education_addition_data',
            field=jsonfield.fields.JSONField(default={'languages': []}, max_length=200, verbose_name='Дополнительные данные для работы системы задач'),
        ),
    ]
