# Generated by Django 3.0.1 on 2021-01-24 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20201209_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puples',
            name='education_level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(998)], verbose_name='Уровень в системе решения задач'),
        ),
    ]
