# Generated by Django 3.0.1 on 2020-11-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20201101_2341'),
        ('market', '0007_auto_20200905_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtproduct',
            name='product_full_name',
            field=models.TextField(default='', max_length=622, verbose_name='Полное название из главного товара'),
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='products_photo/', verbose_name='Фотография главного товара'),
        ),
        migrations.AddField(
            model_name='marketproduct',
            name='visibility_to_customers',
            field=models.BooleanField(default=False, verbose_name='Отображается ли товар покупателям'),
        ),
        migrations.AlterField(
            model_name='boughtproduct',
            name='connected_event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Events', verbose_name='Ссылка на Student Event с этой покупкой'),
        ),
        migrations.AlterField(
            model_name='boughtproduct',
            name='main_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.MarketProduct', verbose_name='Ссылка на основной товар'),
        ),
    ]
