# Generated by Django 3.0.1 on 2020-11-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20201103_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtproduct',
            name='product_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена главного товара'),
        ),
    ]
