# Generated by Django 3.0.1 on 2020-09-21 19:49

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0011_auto_20200902_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('task_name', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description_task', tinymce.models.HTMLField(verbose_name='Описание задачи')),
                ('input_1', tinymce.models.HTMLField(null=True, verbose_name='Входные данные 1(Может быть пустым)')),
                ('output_1', tinymce.models.HTMLField(null=True, verbose_name='Выходные данные 1(Может быть пустым)')),
                ('input_2', tinymce.models.HTMLField(null=True, verbose_name='Входные данные 2(Может быть пустым)')),
                ('output_2', tinymce.models.HTMLField(null=True, verbose_name='Выходные данные 2(Может быть пустым)')),
                ('input_3', tinymce.models.HTMLField(null=True, verbose_name='Входные данные 3(Может быть пустым)')),
                ('output_3', tinymce.models.HTMLField(null=True, verbose_name='Выходные данные 3(Может быть пустым)')),
                ('points_for_right_answer', models.PositiveIntegerField(verbose_name='Количество баллов за правильный ответ')),
                ('visibility', models.BooleanField(default=False, verbose_name='Видимость задачи для учеников')),
            ],
        ),
        migrations.CreateModel(
            name='CheckedEducationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.TextField(verbose_name='Решение задачи в виде кода')),
                ('first_peer_report', models.TextField(verbose_name='Комментарии 1 пира в определенном формате')),
                ('first_peer_mark', models.PositiveIntegerField(null=True, verbose_name='Оценка пира 1')),
                ('second_peer_report', models.TextField(verbose_name='Комментарии 2 пира в определенном формате')),
                ('second_peer_mark', models.PositiveIntegerField(null=True, verbose_name='Оценка пира 2')),
                ('contest_token', models.CharField(max_length=200, verbose_name='Токен для Яндекс.Контест')),
                ('first_peer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_the_first_peer', to='mainapp.Puples', verbose_name='Пир 1')),
                ('original_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hard_tacks_education_system.EducationTask', verbose_name='Оригинал задачи')),
                ('second_peer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_the_second_peer', to='mainapp.Puples', verbose_name='Пир 2')),
                ('solved_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_task', to='mainapp.Puples', verbose_name='Человек, отправивший на проверку')),
            ],
        ),
    ]
