# Generated by Django 3.0.1 on 2020-09-21 20:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkededucationtask',
            options={'verbose_name': 'Решенная и отправленная задача', 'verbose_name_plural': 'Решенные и отправленные задачи'},
        ),
        migrations.AlterModelOptions(
            name='educationtask',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='educationtask',
            name='input_form',
            field=tinymce.models.HTMLField(null=True, verbose_name='Формат ввода'),
        ),
        migrations.AddField(
            model_name='educationtask',
            name='output_form',
            field=tinymce.models.HTMLField(null=True, verbose_name='Формат вывода'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='input_1',
            field=tinymce.models.HTMLField(null=True, verbose_name='Входные данные 1 (Может быть пустым)'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='input_2',
            field=tinymce.models.HTMLField(null=True, verbose_name='Входные данные 2 (Может быть пустым)'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='input_3',
            field=tinymce.models.HTMLField(null=True, verbose_name='Входные данные 3 (Может быть пустым)'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='output_1',
            field=tinymce.models.HTMLField(null=True, verbose_name='Выходные данные 1 (Может быть пустым)'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='output_2',
            field=tinymce.models.HTMLField(null=True, verbose_name='Выходные данные 2 (Может быть пустым)'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='output_3',
            field=tinymce.models.HTMLField(null=True, verbose_name='Выходные данные 3 (Может быть пустым)'),
        ),
    ]
