# Generated by Django 3.0.1 on 2020-10-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0002_auto_20200921_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckedEducationTask',
        ),
        migrations.DeleteModel(
            name='EducationTask',
        ),
    ]
