# Generated by Django 3.0.1 on 2020-10-31 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0004_checkededucationtask_educationlevel_educationtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkededucationtask',
            options={'verbose_name': 'Решенная задача', 'verbose_name_plural': 'Решенные задачи'},
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'verbose_name': 'Уровень для задач', 'verbose_name_plural': 'Уровни для задач'},
        ),
        migrations.AlterModelOptions(
            name='educationtask',
            options={'verbose_name': 'Задача для решения', 'verbose_name_plural': 'Задачи для решения'},
        ),
    ]
