# Generated by Django 3.0.1 on 2020-10-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0005_auto_20201101_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='level_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень группы задач'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='description_task',
            field=models.TextField(verbose_name='Условие задачи'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='example_input_1',
            field=models.TextField(blank=True, verbose_name='Пример 1 ввод'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='example_input_2',
            field=models.TextField(blank=True, verbose_name='Пример 2 ввод'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='example_input_3',
            field=models.TextField(blank=True, verbose_name='Пример 3 ввод'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='example_output_1',
            field=models.TextField(blank=True, verbose_name='Пример 1 вывод'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='example_output_2',
            field=models.TextField(blank=True, verbose_name='Пример 2 вывод'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='example_output_3',
            field=models.TextField(blank=True, verbose_name='Пример 3 вывод'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='input_format',
            field=models.TextField(verbose_name='Формат ввода'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='output_format',
            field=models.TextField(verbose_name='Формат вывода'),
        ),
    ]
