# Generated by Django 3.0.1 on 2020-11-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0007_educationtask_for_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkededucationtask',
            name='task_programming_language',
            field=models.CharField(default='py', max_length=32, verbose_name='Язык программирования, на котором написана задача'),
        ),
    ]
