# Generated by Django 3.0.1 on 2020-11-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0008_checkededucationtask_task_programming_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkededucationtask',
            name='solution_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время, когда принято решение'),
        ),
    ]
