# Generated by Django 3.0.1 on 2020-11-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0009_checkededucationtask_solution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkededucationtask',
            name='task_programming_language',
            field=models.CharField(default='Python 3.7.3', max_length=32, verbose_name='Язык программирования, на котором написана задача'),
        ),
    ]
