# Generated by Django 3.0.1 on 2020-11-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0015_auto_20201104_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkededucationtask',
            name='solution_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время, когда принято решение'),
        ),
    ]
