# Generated by Django 3.0.1 on 2020-11-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0016_auto_20201104_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='level_number',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Уровень группы задач'),
        ),
    ]
