# Generated by Django 3.0.1 on 2020-12-07 20:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0018_auto_20201116_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkededucationtask',
            name='test_array_json',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
