# Generated by Django 3.0.1 on 2020-12-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0019_checkededucationtask_test_array_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkededucationtask',
            name='test_array_json',
        ),
    ]
