# Generated by Django 3.0.1 on 2020-12-25 00:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20201209_1326'),
        ('hard_tacks_education_system', '0020_remove_checkededucationtask_test_array_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkededucationtask',
            name='contest_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Токен для Яндекс.Контест'),
        ),
        migrations.AlterField(
            model_name='checkededucationtask',
            name='first_peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Peer_1', to='mainapp.Puples', verbose_name='Peer 1'),
        ),
        migrations.AlterField(
            model_name='checkededucationtask',
            name='first_peer_mark',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка peer 1'),
        ),
        migrations.AlterField(
            model_name='checkededucationtask',
            name='result_summ_mark',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Общий итог всех оценок'),
        ),
        migrations.AlterField(
            model_name='checkededucationtask',
            name='second_peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Peer_2', to='mainapp.Puples', verbose_name='Peer 2'),
        ),
        migrations.AlterField(
            model_name='checkededucationtask',
            name='second_peer_mark',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка peer 2'),
        ),
        migrations.AlterField(
            model_name='checkededucationtask',
            name='system_mark',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка Яндекс.Контест'),
        ),
    ]
