# Generated by Django 3.0.1 on 2021-01-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hard_tacks_education_system', '0021_auto_20201225_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkededucationtask',
            name='original_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hard_tacks_education_system.EducationTask', verbose_name='Оригинал задачи'),
        ),
    ]
