# Generated by Django 3.0.1 on 2020-10-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytask', '0004_auto_20200916_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='result',
            field=models.CharField(max_length=200, null=True, verbose_name='Правильный ответ на задачу'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status_task',
            field=models.CharField(choices=[('ST10', '10 класс'), ('ST11', '11 класс')], default='ST10', max_length=30, verbose_name='Выберите класс'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tries',
            field=models.IntegerField(default=-1, verbose_name='Количество попыток ответа на каждого ученика (-1 - бесконечно)'),
        ),
    ]
